- name: Education
  slug: education
  contains:
  - name: DHC
    slug: dhc  # slugs are optional
  - name: GLI
    slug: gli


- name: Hobbies
  slug: hobbies
  contains:
  - name: Code
    slug: code
  - name: Scouts
    slug: scouts
  - name: Theatre
    slug: theatre
    contains:
    - name: Homelab
      slug: homelab


- name: Resume
  slug: resume
  style:
    classes: [is-bold]  # CSS classes
